spring.application.name=IotCore

# Server Context Root and Port
server.port=8080

# Logging
logging.level.root=INFO

#ASK SDK Configuration
com.amazon.ask.servlet.disableRequestSignatureCheck=true
com.amazon.speech.speechlet.servlet.timestampTolerance=3600000
#javax.net.ssl.keyStore=YOUR-KEYSTORE-FILE-PATH-HERE
#javax.net.ssl.keyStorePassword=YOUR-KEYSTOREPASSWORD-HERE

#MongoDB Configuration
spring.data.mongodb.database=iot-core
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PSW}@${MONGO_HOST:localhost}/iot-core?retryWrites=true&w=majority&appName=MongoDBCluster
spring.data.mongodb.auto-index-creation=true
